---
- name: Setting elrepo_version fact (el7)
  set_fact:
    elrepo_version: "7.0-3.el7"
  when: elrepo_dist == '7'

- name: Setting elrepo_version fact (el6)
  set_fact:
    elrepo_version: "6-8.el6"
  when: elrepo_dist == '6'

- name: Attempting to create temporary file
  tempfile:
    prefix: 'elrepo.'
    state: file
    suffix: '.rpm'
  register: elrepo_tempfile

- name: Temp
  debug: var=elrepo_tempfile

- name: Downloading package to temporary location
  get_url:
    dest: "{{ elrepo_tempfile.path }}"
    force: yes
    url: "https://www.elrepo.org/elrepo-release-{{ elrepo_version }}.elrepo.noarch.rpm"
  register: elrepo_get_url
  when: elrepo_tempfile is success

- name: Ensure that the elrepo-release package is installed
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: elrepo_yum
  with_items: "{{ elrepo_tempfile.path }}"
  when: elrepo_get_url is success

- name: Purging temporary package from filesystem
  file:
    path: "{{ elrepo_tempfile.path }}"
    state: absent
  when:
    - elrepo_tempfile is success
    - elrepo_yum is success

- name: Applying elrepo repository configurations
  become: true
  template:
    src: elrepo.repo.j2
    dest: /etc/yum.repos.d/elrepo.repo
    owner: root
    group: root
    mode: 0644
  when: elrepo_yum is success

- name: Ensure that the ELRepo GPG keys are installed
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    state: present
  when: elrepo_yum is success

- name: Ensure that the required elrepo packages are installed
  become: true
  yum:
    disable_plugin: "{{ elrepo_disable_plugin|join(',') }}"
    disablerepo: "{{ elrepo_disablerepo|join(',') }}"
    enable_plugin: "{{ elrepo_enable_plugin|join(',') }}"
    enablerepo: "{{ elrepo_enablerepo|join(',') }}"
    name: "{{ item }}"
    state: present
  with_items: "{{ elrepo_packages }}"
  when:
    - elrepo_packages|length > 0
    - elrepo_yum is success
...
