---
- name: Setting elrepo_version fact (el7)
  set_fact:
    elrepo_version: "7.0-3.el7"
  when: elrepo_dist == '7'

- name: Setting elrepo_version fact (el6)
  set_fact:
    elrepo_version: "6-8.el6"
  when: elrepo_dist == '6'

- name: Setting elrepo_version fact (el5)
  set_fact:
    elrepo_version: "5-5.el5"
  when: elrepo_dist == '5'

- name: Generating temporary filename via mktemp
  command: |
    mktemp -u --suffix .rpm
  register: elrepo_mktemp

- name: Downloading package to temporary location
  get_url:
    dest: "{{ elrepo_mktemp.stdout }}"
    url: "https://www.elrepo.org/elrepo-release-{{ elrepo_version }}.elrepo.noarch.rpm"
  register: elrepo_get_url
  when: elrepo_mktemp|success

- name: Ensure that the elrepo-release package is installed
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: elrepo_yum
  with_items: "{{ elrepo_mktemp.stdout }}"
  when: elrepo_get_url|success

- name: Applying elrepo repository configurations
  become: true
  template:
    src: elrepo.repo.j2
    dest: /etc/yum.repos.d/elrepo.repo
    owner: root
    group: root
    mode: 0644
  when: elrepo_yum|success

- name: Ensure that the ELRepo GPG keys are installed
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    state: present
  when: elrepo_yum|success

- name: Purging temporary package from filesystem
  file:
    path: "{{ elrepo_mktemp.stdout }}"
    state: absent
  when:
    - elrepo_mktemp|success
    - elrepo_yum|success
...
