---
- name: Assert that the prerequisites are defined
  assert:
    that:
      - elrepo_pkg is defined
      - elrepo_rel is defined

- name: Setting elrepo_ver fact (el7)
  set_fact:
    elrepo_ver: "7.0-3.el7"
  when: elrepo_rel == '7'

- name: Setting elrepo_ver fact (el6)
  set_fact:
    elrepo_ver: "6-8.el6"
  when: elrepo_rel == '6'

- name: Setting elrepo_ver fact (el5)
  set_fact:
    elrepo_ver: "5-5.el5"
  when: elrepo_rel == '5'

- name: Generating temporary filename via mktemp
  command: mktemp -u --suffix .rpm
  register: elrepo_mktemp

- name: Downloading package to temporary location
  get_url:
    url: "https://www.elrepo.org/{{ elrepo_pkg }}-{{ elrepo_ver }}.elrepo.noarch.rpm"
    dest: "{{ elrepo_mktemp.stdout }}"
  register: elrepo_get_url
  when: elrepo_mktemp|success

- name: Ensure that the elrepo-release package is installed
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: elrepo_yum
  with_items: "{{ elrepo_mktemp.stdout }}"
  when: elrepo_get_url|success

- name: Applying elrepo.repo configurations
  become: true
  template:
    src: elrepo.repo.j2
    dest: /etc/yum.repos.d/elrepo.repo
    owner: root
    group: root
    mode: 0644
  when: elrepo_yum|success

- name: Ensure that the ELRepo GPG keys are installed
  become: true
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
    state: present

- name: Purging temporary package from filesystem
  file:
    path: "{{ elrepo_mktemp.stdout }}"
    state: absent
  when:
    - elrepo_mktemp|success
    - elrepo_yum|success
...
