---
- include: install_repo.yml
  when:
    - ansible_os_family == "RedHat"

- include: install_kernel.yml
  when:
    - ansible_os_family == "RedHat"
    - elrepo_kernel_install is defined
    - elrepo_kernel_install
...
