---
- name: Attempting to import elrepo tasks
  tags: elrepo
  block:
    - import_tasks: elrepo_repository.yml
    - import_tasks: elrepo_kernel.yml
      when:
        - elrepo_kernel|bool
        - elrepo_yum is success
  when: ansible_os_family == 'RedHat'
...
